version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-esoja
    restart: always
    environment:
      - POSTGRES_DB=esoja
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
  redis:
    image: redis
    container_name: redis-esoja
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - '6379:6379'
